import os
import subprocess
import sys

# --- Paths (derived from this script's location) ---
SLURM_DIR = os.path.dirname(os.path.abspath(__file__))
MUONCOLLIDER_DIR = os.path.dirname(SLURM_DIR)

# --- Configuration ---
NUM_JOBS = 500             # Number of jobs per process
NEVENTS_PER_JOB = 20      # Events per job -> 500 x 20 = 10k events per boson, 30k total
OUTPUT_BASE_DIR = os.path.join(MUONCOLLIDER_DIR, "output/vbf_inclusive_production_10k")
MUCOLL_BENCHMARKS_PATH = os.path.join(MUONCOLLIDER_DIR, "mucoll-benchmarks")

APPTAINER_IMAGE = os.path.join(SLURM_DIR, "mucoll-sim.sif")

# Gridpack directories for the inclusive 2->4 processes (generated by make_gridpack.py)
_GP = os.path.join(MUONCOLLIDER_DIR, "output/gridpacks")

# --- Processes to submit ---
# SET=4: 2->4 inclusive ME, gridpacks pre-computed via make_gridpack.py
PROCESSES = [
    ("vbfZ_inclusive", os.path.join(SLURM_DIR, "chains/run_chain_vbfZ.sh"),
     ["4"], os.path.join(_GP, "grid_mumu_vbfZqq_inclusive")),
    ("vbfH_inclusive", os.path.join(SLURM_DIR, "chains/run_chain_vbfH.sh"),
     ["4"], os.path.join(_GP, "grid_mumu_vbfHbb_inclusive")),
    ("vbfW_inclusive", os.path.join(SLURM_DIR, "chains/run_chain_vbfW.sh"),
     ["4"], os.path.join(_GP, "grid_mumu_vbfWqq_inclusive")),
]


def unpack(entry):
    """Return (label, script_path, extra_args, gridpack_dir) for an entry."""
    if len(entry) == 2:
        label, script = entry
        return label, script, [], GRIDPACK_DIR
    if len(entry) == 4:
        label, script, extras, grid = entry
        return label, script, list(extras), (grid if grid is not None else GRIDPACK_DIR)
    raise ValueError(f"Bad PROCESSES entry (need 2 or 4 fields): {entry}")

# --- Validation ---
if not os.path.exists(MUCOLL_BENCHMARKS_PATH):
    print(f"Error: Benchmarks path not found: {MUCOLL_BENCHMARKS_PATH}")
    sys.exit(1)

for entry in PROCESSES:
    label, script_path, _, _ = unpack(entry)
    if not os.path.exists(script_path):
        print(f"Error: Script not found for {label}: {script_path}")
        sys.exit(1)
    os.chmod(script_path, 0o755)

if not os.path.exists(APPTAINER_IMAGE):
    print(f"Error: Container image not found: {APPTAINER_IMAGE}")
    print(f"Pull it first with:")
    print(f"  apptainer pull {APPTAINER_IMAGE} docker://ghcr.io/muoncollidersoft/mucoll-sim-ubuntu24:main")
    sys.exit(1)

# Safety check: ensure new output dir does not shadow the existing 500-event sample dir
PROTECTED_DIR = os.path.join(MUONCOLLIDER_DIR, "output/vbf_inclusive_production")
if os.path.realpath(OUTPUT_BASE_DIR) == os.path.realpath(PROTECTED_DIR):
    print(f"Error: OUTPUT_BASE_DIR would overwrite protected directory: {PROTECTED_DIR}")
    sys.exit(1)

os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)
print(f"Submitting {NUM_JOBS} jobs x {len(PROCESSES)} process(es) = {NUM_JOBS * len(PROCESSES)} total jobs.")
print(f"Output will be in {OUTPUT_BASE_DIR}")

# Launch jobs for each process specified above.
for entry in PROCESSES:
    label, script_path, extra_args, gridpack = unpack(entry)
    print(f"\n--- Process: {label} ---")
    extra_str = " ".join(extra_args)
    for job_id in range(NUM_JOBS):
        job_name = f"mucoll_{label}_{job_id}"
        log_dir = os.path.join(OUTPUT_BASE_DIR, "logs")
        os.makedirs(log_dir, exist_ok=True)

        slurm_script = f"""#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output={log_dir}/{label}_job_{job_id}.out
#SBATCH --error={log_dir}/{label}_job_{job_id}.err
#SBATCH --time=10:00:00
#SBATCH --mem=16G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --qos=avery-b

echo "Running on host: $(hostname)"
echo "Process: {label}  Job ID: {job_id}"

# Run the container (--cleanenv prevents host Python env vars from breaking container Python)
apptainer exec --cleanenv --bind {MUONCOLLIDER_DIR} {APPTAINER_IMAGE} bash {script_path} {job_id} {NEVENTS_PER_JOB} {OUTPUT_BASE_DIR} {MUCOLL_BENCHMARKS_PATH} {extra_str} {gridpack}
"""

        script_filename = f"submit_{label}_{job_id}.sh"
        with open(script_filename, "w") as f:
            f.write(slurm_script)

        try:
            result = subprocess.run(["sbatch", script_filename], capture_output=True, text=True, check=True)
            print(f"  Submitted {label} job {job_id}: {result.stdout.strip()}")
        except subprocess.CalledProcessError as e:
            print(f"  Error submitting {label} job {job_id}: {e.stderr}")
        finally:
            if os.path.exists(script_filename):
                os.remove(script_filename)

print("Submission complete.")
